<?php

/**
 * This is the model base class for the table "common".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Common".
 *
 * Columns in table "common" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $siteName
 * @property string $siteCreed
 * @property string $siteDescription
 * @property string $siteEmail
 * @property string $sitePhone
 * @property string $seo_keywords
 * @property string $seo_description
 * @property string $seo_author
 * @property integer $siteEnabled
 *
 */
abstract class BaseCommon extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'common';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Common|Commons', $n);
	}

	public static function representingColumn() {
		return 'siteName';
	}

	public function rules() {
		return array(
			array('siteEnabled', 'numerical', 'integerOnly'=>true),
			array('siteName, siteCreed, siteEmail, sitePhone, seo_keywords, seo_author', 'length', 'max'=>255),
			array('siteDescription, seo_description', 'safe'),
			array('siteName, siteCreed, siteDescription, siteEmail, sitePhone, seo_keywords, seo_description, seo_author, siteEnabled', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, siteName, siteCreed, siteDescription, siteEmail, sitePhone, seo_keywords, seo_description, seo_author, siteEnabled', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'siteName' => Yii::t('app', 'Site Name'),
			'siteCreed' => Yii::t('app', 'Site Creed'),
			'siteDescription' => Yii::t('app', 'Site Description'),
			'siteEmail' => Yii::t('app', 'Site Email'),
			'sitePhone' => Yii::t('app', 'Site Phone'),
			'seo_keywords' => Yii::t('app', 'Seo Keywords'),
			'seo_description' => Yii::t('app', 'Seo Description'),
			'seo_author' => Yii::t('app', 'Seo Author'),
			'siteEnabled' => Yii::t('app', 'Site Enabled'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('siteName', $this->siteName, true);
		$criteria->compare('siteCreed', $this->siteCreed, true);
		$criteria->compare('siteDescription', $this->siteDescription, true);
		$criteria->compare('siteEmail', $this->siteEmail, true);
		$criteria->compare('sitePhone', $this->sitePhone, true);
		$criteria->compare('seo_keywords', $this->seo_keywords, true);
		$criteria->compare('seo_description', $this->seo_description, true);
		$criteria->compare('seo_author', $this->seo_author, true);
		$criteria->compare('siteEnabled', $this->siteEnabled);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}