<?php

/**
 * This is the model base class for the table "Users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Users".
 *
 * Columns in table "Users" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $email
 * @property string $name
 * @property string $password
 * @property string $avatar
 * @property string $phone
 * @property string $role
 * @property integer $is_active
 * @property integer $rememberMe
 * @property string $dateCreate
 * @property string $dateChange
 * @property string $dateLastLogin
 *
 */
abstract class BaseUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'Users';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Users|Users', $n);
	}

	public static function representingColumn() {
		return 'email';
	}

	public function rules() {
		return array(
			array('email, password', 'required'),
			array('is_active, rememberMe', 'numerical', 'integerOnly'=>true),
			array('email, name, password, avatar', 'length', 'max'=>255),
			array('phone', 'length', 'max'=>30),
			array('role', 'length', 'max'=>60),
			array('dateChange, dateLastLogin', 'safe'),
			array('email, name, password, avatar, phone, role, is_active, rememberMe, dateChange, dateLastLogin', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, email, name, password, avatar, phone, role, is_active, rememberMe, dateCreate, dateChange, dateLastLogin', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'email' => Yii::t('app', 'Email'),
			'name' => Yii::t('app', 'Name'),
			'password' => Yii::t('app', 'Password'),
			'avatar' => Yii::t('app', 'Avatar'),
			'phone' => Yii::t('app', 'Phone'),
			'role' => Yii::t('app', 'Role'),
			'is_active' => Yii::t('app', 'Is Active'),
			'rememberMe' => Yii::t('app', 'Remember Me'),
			'dateCreate' => Yii::t('app', 'Date Create'),
			'dateChange' => Yii::t('app', 'Date Change'),
			'dateLastLogin' => Yii::t('app', 'Date Last Login'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('avatar', $this->avatar, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('role', $this->role, true);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('rememberMe', $this->rememberMe);
		$criteria->compare('dateCreate', $this->dateCreate, true);
		$criteria->compare('dateChange', $this->dateChange, true);
		$criteria->compare('dateLastLogin', $this->dateLastLogin, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}